import xarray as xr
import numpy as np

def similarity_nrmse(a, b):
    """
    基于归一化RMSE的相似度（0~100%）
    """
    diff = a - b
    rmse = np.sqrt(np.nanmean(diff ** 2))

    data_min = np.nanmin([a.min(), b.min()])
    data_max = np.nanmax([a.max(), b.max()])
    data_range = data_max - data_min

    if data_range == 0:
        return 100.0

    similarity = (1 - rmse / data_range) * 100
    return max(0.0, similarity)


def compare_nc_similarity(nc1_path, nc2_path, variables):
    ds1 = xr.open_dataset(nc1_path)
    ds2 = xr.open_dataset(nc2_path)

    results = {}

    for var in variables:
        if var not in ds1 or var not in ds2:
            print(f"[WARN] {var} not found in both files")
            continue

        da1 = ds1[var].astype(np.float64)
        da2 = ds2[var].astype(np.float64)

        # 对齐坐标（防止 lat / lon 顺序或精度差异）
        da1, da2 = xr.align(da1, da2, join="exact")

        # 转 numpy 并 mask NaN / FillValue
        a = da1.values
        b = da2.values

        similarity = similarity_nrmse(a, b)
        results[var] = similarity

    return results


if __name__ == "__main__":
    nc_gdas = r"E:\pyCharmProject\pangu\model_input\gdas_fnl\2025-08-01-00-00gdas_fnl\surface.nc"
    nc_ecmwf = r"E:\pyCharmProject\pangu\model_input\era5\2025-08-01-00-00\surface.nc"

    variables = ["u10", "v10", "t2m", "msl"]

    sim = compare_nc_similarity(nc_gdas, nc_ecmwf, variables)

    for k, v in sim.items():
        print(f"{k:5s} 相似度：{v:.2f}%")

'''
(pangu) PS E:\pyCharmProject\pangu> ncdump -h E:\pyCharmProject\pangu\gdas\surface.nc                                
netcdf surface {
dimensions:
        time = UNLIMITED ; // (1 currently)
        latitude = 721 ;
        longitude = 1440 ;
variables:
        float msl(time, latitude, longitude) ;
                msl:_FillValue = NaNf ;
                msl:short_name = "PRMSL_meansealevel" ;
                msl:long_name = "Pressure Reduced to MSL" ;
                msl:level = "mean sea level" ;
                msl:units = "Pa" ;
        float u10(time, latitude, longitude) ;
                u10:_FillValue = NaNf ;
                u10:short_name = "UGRD_10maboveground" ;
                u10:long_name = "U-Component of Wind" ;
                u10:level = "10 m above ground" ;
                u10:units = "m/s" ;
        float v10(time, latitude, longitude) ;
                v10:_FillValue = NaNf ;
                v10:short_name = "VGRD_10maboveground" ;
                v10:long_name = "V-Component of Wind" ;
                v10:level = "10 m above ground" ;
                v10:units = "m/s" ;
        float t2m(time, latitude, longitude) ;
                t2m:_FillValue = NaNf ;
                t2m:short_name = "TMP_2maboveground" ;
                t2m:long_name = "Temperature" ;
                t2m:level = "2 m above ground" ;
                t2m:units = "K" ;
        float sp(time, latitude, longitude) ;
                sp:_FillValue = NaNf ;
                sp:short_name = "PRES_surface" ;
                sp:long_name = "Pressure" ;
                sp:level = "surface" ;
                sp:units = "Pa" ;
        double latitude(latitude) ;
                latitude:_FillValue = NaN ;
                latitude:units = "degrees_north" ;
                latitude:long_name = "latitude" ;
                latitude:axis = "Y" ;
        double longitude(longitude) ;
                longitude:_FillValue = NaN ;
                longitude:units = "degrees_east" ;
                longitude:long_name = "longitude" ;
        double time(time) ;
                time:_FillValue = NaN ;
                time:long_name = "verification time generated by wgrib2 function verftime()" ;
                time:reference_time = 1536624000. ;
                time:reference_time_type = 1 ;
                time:reference_date = "2018.09.11 00:00:00 UTC" ;
                time:reference_time_description = "analyses, reference date is fixed" ;
                time:time_step_setting = "auto" ;
                time:time_step = 0. ;
                time:units = "seconds since 1970-01-01" ;
                time:calendar = "proleptic_gregorian" ;

// global attributes:
                :Conventions = "COARDS" ;
                :History = "created by wgrib2" ;
                :GRIB2_grid_template = 0 ;
}'''